name: open_api_generator
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: joeconway <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  open_api: ^2.0.1

dev_dependencies:
  test: ^1.3.4
